FROM debian:8.7
MAINTAINER Pedro Sanders <fonosterteam@fonoster.com>

RUN apt-get -yqq update
RUN apt-get -yqq install curl lsb-release
RUN curl -L https://getchef.com/chef/install.sh | bash -s -- -v 12.9.41
RUN apt-get -yqq clean

COPY chef-repo /var/chef-repo
RUN /usr/bin/chef-solo -o "role[apps_server]" -c /var/chef-repo/solo.rb

EXPOSE 4573
EXPOSE 8080
EXPOSE 8443
EXPOSE 5060
EXPOSE 5061
EXPOSE 5062

RUN chmod +x /var/chef-repo/etc/run_app.sh

ENTRYPOINT ["/bin/sh"]
CMD ["/var/chef-repo/etc/run_app.sh"]
