---
driver:
  name: docker

provisioner:
  name: chef_solo
  coobooks_path:
    - berks-cookbooks

platforms:
  - name: ubuntu-16.04

suites:
  - name: apps-server
    run_list:
        - role[apps_server]
    attributes:
  - name: asterisk-server
    run_list:
        - recipe[fn_asterisk]
    attributes:
