apiVersion: v1
kind: Service
metadata:
  name: fnmongodb
  labels:
    app: fonoster
spec:
  ports:
    - port: 27017
  selector:
    app: fonoster
    tier: data
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fnmongodb
  labels:
    app: fonoster
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fonoster
        tier: data
    spec:
      containers:
      - name: fnmongodb
        image: gcr.io/fonoster-app/fnmongodb:IMAGE_VERSION
        imagePullPolicy: Always
        env:
        - name: FONOSTER_ENV
          value: prod               # If set to dev it will create the initial database (or dev db)
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongo-storage
          mountPath: /var/lib/mongodb
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: pvc0001
