apiVersion: v1
kind: Service
metadata:
    name: site
    labels:
        app: fonoster
spec:
    ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
    selector:
      app: fonoster
      tier: frontend
    type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fnsite
  labels:
    app: fonoster
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fonoster
        tier: frontend
    spec:
      containers:
      - name: fnsite
        image: gcr.io/fonoster-app/fnsite:IMAGE_VERSION
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
