# PVC for mongo files
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc0002
  labels:
    app: fonoster
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
